df <- subset(read.csv('household_power_consumption.txt', sep = ';', na.strings='?'), Date == '1/2/2007' | Date == '2/2/2007') 
dateTime = strptime(paste(as.character(df$Date), as.character(df$Time)), format="%d/%m/%Y %H:%M:%S")
png(filename = "plot3.png", width = 480, height = 480)
plot(x=dateTime, y=df$Sub_metering_1, type = 'n', ylab='Energy sub metering', xlab='')
lines(dateTime, df$Sub_metering_1, col='black')
lines(dateTime, df$Sub_metering_2, col='red')
lines(dateTime, df$Sub_metering_3, col='blue')
legend('topright', col = c('black', 'red', 'blue'), lty = 'solid',  legend=c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'))
dev.off()