df <- subset(read.csv('household_power_consumption.txt', sep = ';', na.strings='?'), Date == '1/2/2007' | Date == '2/2/2007') 
dateTime = strptime(paste(as.character(df$Date), as.character(df$Time)), format="%d/%m/%Y %H:%M:%S")
png(filename = "plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(dateTime, df$Global_active_power, type = 'n', ylab='Global Active Power', xlab='')
lines(dateTime, df$Global_active_power)
plot(dateTime, df$Voltage, type = 'n', ylab='Voltage', xlab='datetime')
lines(dateTime, df$Voltage)
plot(x=dateTime, y=df$Sub_metering_1, type = 'n', ylab='Energy sub metering', xlab='')
lines(dateTime, df$Sub_metering_1, col='black')
lines(dateTime, df$Sub_metering_2, col='red')
lines(dateTime, df$Sub_metering_3, col='blue')
legend('topright', bty='n', col = c('black', 'red', 'blue'), lty = 'solid',  legend=c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'))
plot(x=dateTime, y=df$Global_reactive_power, type = 'n', ylab='Global_reactive_power', xlab='datetime')
lines(dateTime, df$Global_reactive_power)
dev.off()